import '@/styles/globals.css';
import { Ubuntu, Ubuntu_Mono } from 'next/font/google';
import NavBar from '@/components/navigation/navBar';
import Footer from '@/components/navigation/footer';
import ReduxProvider from '@/redux/provider';
import ThemeProvider from '@/components/theme/ThemeProvider';


const ubuntu = Ubuntu({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'],
	style: ['normal', 'italic'],
	display: 'swap',
	variable: '--font-ubuntu',
});
const ubuntu_mono = Ubuntu_Mono({
	subsets: ['latin'],
	weight: ['400', '700'],
	style: ['normal', 'italic'],
	display: 'swap',
	variable: '--font-ubuntu_mono',
});

const metadata = {
	title: 'Djimmi | Hire talent or find a job',
	description: 'Generated by create next app',
};

const RootLayout = ({ children, }: { children: React.ReactNode }) => {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			className='scroll-smooth'
		>
			<body className={`${ubuntu.variable} ${ubuntu_mono.variable} bg-main-light dark:bg-main`}>
				<ThemeProvider>
					<ReduxProvider>
						<NavBar />
						{children}
						<Footer />
					</ReduxProvider>
				</ThemeProvider>
			</body>
		</html>
	);
};


export default RootLayout;
export { metadata, ubuntu, ubuntu_mono };