import './globals.css';
import { Inter } from 'next/font/google';
import NavBar from '@/components/navigation/navBar';
import Footer from '@/components/navigation/footer';
import ReduxProvider from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
    title: 'Djimmi | Hire talent or find a job',
    description: 'Generated by create next app',
};

const RootLayout = ({ children, }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    <NavBar />
                    {children}
                    <Footer />
                </ReduxProvider>
            </body>
        </html>
    );
};


export default RootLayout;
export { metadata };